import { test, expect } from '@playwright/test'
const token='sv_operator_'+'B'.repeat(43)
const caseId='00000000-0000-0000-0000-000000000014'
const probe='**/api/v2/investigation/evidence?limit=1'

test('masked connection uses existing probe, keyboard loading and no hidden reads',async({page})=>{
  const requests:string[]=[], logs:string[]=[]
  page.on('request',request=>requests.push(request.url()))
  page.on('console',message=>logs.push(message.text()))
  let release!:()=>void
  const gate=new Promise<void>(resolve=>{release=resolve})
  await page.route(probe,async route=>{
    expect(route.request().headers().authorization).toBe(`Bearer ${token}`)
    expect(route.request().method()).toBe('GET')
    await gate;await route.fulfill({json:{items:[],total:0,next_cursor:null}})
  })
  await page.goto('/#login')
  await expect(page).toHaveTitle('Operator connection | ShadowVault AI')
  await expect(page.getByRole('heading',{name:'Connect operator'})).toBeVisible()
  await expect(page.getByLabel('Email address')).toHaveCount(0)
  await expect(page.getByLabel('Password',{exact:true})).toHaveCount(0)
  const input=page.getByLabel('Operator token',{exact:true})
  await expect(input).toHaveAttribute('type','password')
  await expect(page.getByRole('button',{name:/show.*token/i})).toHaveCount(0)
  await input.fill(token);await input.press('Enter')
  await expect(input).toHaveValue('');await expect(input).toBeDisabled()
  await expect(page.getByText('Checking operator access…')).toBeVisible()
  await expect(page.locator('form')).toHaveAttribute('aria-busy','true')
  expect(requests.filter(url=>url.includes('/api/v2/'))).toHaveLength(1)
  release()
  await expect(page.getByText('Operator connected',{exact:true})).toBeFocused()
  await expect(page.getByRole('link',{name:'Open cases',exact:true})).toBeVisible()
  expect(requests.filter(url=>url.includes('/api/v2/'))).toHaveLength(1)
  expect(requests.some(url=>url.includes('/auth/login')||url.includes(token))).toBe(false)
  expect(logs.join(' ')).not.toContain(token)
  await expect(page.locator('body')).not.toContainText(token)
  await page.getByRole('link',{name:'Open cases',exact:true}).click()
  await expect(page.getByRole('link',{name:'Browser fixture',exact:true})).toBeVisible()
})

test('invalid and rejected credentials stay private and retry is manual',async({page})=>{
  let calls=0
  await page.route(probe,route=>{calls++;return route.fulfill({status:401,json:{detail:token}})})
  await page.goto('/#login')
  const input=page.getByLabel('Operator token',{exact:true})
  await page.getByRole('button',{name:'Connect operator',exact:true}).click()
  expect(calls).toBe(0)
  await input.fill('invalid value');await input.press('Enter')
  await expect(page.getByRole('alert')).toContainText('without quotes')
  expect(calls).toBe(0)
  await expect(input).toBeFocused();await expect(input).toHaveValue('')
  await input.fill(token);await input.press('Enter')
  await expect(page.getByRole('alert')).toContainText('connection rejected')
  await expect(page.getByRole('alert')).not.toContainText(token)
  await expect(input).toHaveValue('');await expect(input).toBeFocused()
  expect(calls).toBe(1)
  await page.unroute(probe)
  await input.fill(token);await input.press('Enter')
  await expect(page.getByText('Operator connected',{exact:true})).toBeVisible()
})

test('network failure provides safe recovery and deep-link protection',async({page})=>{
  await page.route(probe,route=>route.abort('failed'))
  await page.goto(`/#cases/${caseId}`)
  await expect(page.getByRole('heading',{name:'Browser fixture',exact:true})).toHaveCount(0)
  await page.getByLabel('Operator token',{exact:true}).fill(token)
  await page.getByRole('button',{name:'Connect operator',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('retry manually')
  await page.unroute(probe)
  await page.getByLabel('Operator token',{exact:true}).fill(token)
  await page.getByRole('button',{name:'Connect operator',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Browser fixture',exact:true})).toBeVisible()
  await expect(page).toHaveURL(new RegExp('#cases/'+caseId+'$'))
  await page.getByRole('button',{name:'Disconnect operator'}).click()
  await expect(page.getByLabel('Operator token',{exact:true})).toBeFocused()
  await expect(page.getByRole('heading',{name:'Browser fixture',exact:true})).toHaveCount(0)
  expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0])
})

test('expired connection clears case and focuses re-entry without restoring drafts',async({page})=>{
  await page.goto(`/#cases/${caseId}`)
  await page.getByLabel('Operator token',{exact:true}).fill(token)
  await page.getByRole('button',{name:'Connect operator',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Browser fixture',exact:true})).toBeVisible()
  await page.route(`**/incidents/${caseId}`,route=>route.fulfill({status:401,json:{detail:token}}))
  await page.getByRole('button',{name:'Refresh case',exact:true}).click()
  await expect(page.getByLabel('Operator token',{exact:true})).toBeFocused()
  await expect(page.getByRole('alert')).not.toContainText(token)
  await expect(page.getByRole('heading',{name:'Browser fixture',exact:true})).toHaveCount(0)
})

for(const width of [320,390])test(`connection controls and error fit ${width}px with keyboard access`,async({page})=>{
  await page.setViewportSize({width,height:844});await page.goto('/#login')
  await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Skip to content'})).toBeFocused()
  await page.keyboard.press('Enter');await expect(page.locator('main')).toBeFocused()
  const input=page.getByLabel('Operator token',{exact:true})
  await input.fill('invalid');await input.press('Enter')
  await expect(input).toBeFocused()
  await expect(page.getByRole('alert')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await expect(input).toHaveAttribute('aria-describedby',/operator-error/)
})
