import { test, expect, type Page } from '@playwright/test'
const caseId='00000000-0000-0000-0000-000000000014', evidenceId='00000000-0000-0000-0000-000000000001'
async function open(page:Page){
 await page.goto('/#cases');await page.getByLabel('Operator token',{exact:true}).fill('sv_operator_'+'B'.repeat(43))
 await page.getByRole('button',{name:'Connect operator',exact:true}).click()
 await page.getByRole('link',{name:'Browser fixture',exact:true}).click()
 return page.getByRole('region',{name:'Case Threat Intelligence'})
}
async function source(page:Page){await page.locator(`a[href="#cases/${caseId}/evidence/${evidenceId}"]`).first().click()}
test('evidence-context registration filters and correction links preserve provenance',async({page})=>{
 const panel=await open(page);await source(page)
 await page.getByRole('button',{name:'Record indicator for this evidence',exact:true}).click()
 await expect(panel.getByLabel('Indicator evidence ID',{exact:true})).toHaveValue(evidenceId)
 await expect(panel.getByLabel('Indicator evidence ID',{exact:true})).toBeFocused()
 await expect(panel.getByText(/Selected evidence: browser-fixture.bin/)).toBeVisible()
 await panel.getByLabel('Indicator kind',{exact:true}).selectOption('domain')
 await panel.getByLabel('Indicator value',{exact:true}).fill('before.workflow.example')
 const first=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/indicators'))
 await panel.getByRole('button',{name:'Record indicator',exact:true}).click()
 const original=await (await first).json()
 await panel.getByRole('button',{name:'View saved observation',exact:true}).click()
 await panel.getByRole('button',{name:'Correct observation '+original.id,exact:true}).click()
 await expect(panel.getByLabel('Corrects observation ID (optional)',{exact:true})).toHaveValue(original.id)
 await panel.getByLabel('Indicator value',{exact:true}).fill('after.workflow.example')
 const second=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/indicators'))
 await panel.getByRole('button',{name:'Record indicator',exact:true}).click()
 const correction=await (await second).json()
 await expect(panel.getByText('Corrected — original retained.',{exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'View correction '+correction.id,exact:true}).click()
 await expect(panel.getByRole('heading',{name:'domain: after.workflow.example',exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'View original '+original.id,exact:true}).click()
 await panel.getByRole('button',{name:'Clear indicator filters',exact:true}).click()
 await panel.getByLabel('Filter indicator kind',{exact:true}).selectOption('domain')
 await panel.getByLabel('Exact indicator value',{exact:true}).fill('BEFORE.WORKFLOW.EXAMPLE')
 await panel.getByRole('button',{name:'Filter indicators',exact:true}).click()
 await expect(panel.getByText('Corrected — original retained.',{exact:true})).toBeVisible()
 await expect(panel.getByRole('heading',{name:'domain: after.workflow.example',exact:true})).toHaveCount(0)
 await panel.getByRole('link',{name:'Source evidence '+evidenceId,exact:true}).click()
 await page.getByRole('button',{name:'View indicators for this evidence',exact:true}).click()
 await expect(panel.getByLabel('Filter indicator evidence ID',{exact:true})).toHaveValue(evidenceId)
})
test('pending retry survives source navigation and receipt survives refresh failure',async({page})=>{
 const panel=await open(page)
 await panel.getByText('Add indicator observation',{exact:true}).click()
 await panel.getByLabel('Indicator evidence ID',{exact:true}).fill(evidenceId)
 await panel.getByLabel('Indicator kind',{exact:true}).selectOption('domain')
 await panel.getByLabel('Indicator value',{exact:true}).fill('retry.workflow.example')
 const bodies:string[]=[];let fail=true
 await page.route('**/evidence/'+evidenceId+'/indicators',async route=>{bodies.push(route.request().postData()!);if(fail){fail=false;await route.fulfill({status:503,json:{}})}else await route.continue()})
 await panel.getByRole('button',{name:'Record indicator',exact:true}).click()
 await expect(panel.getByRole('alert')).toContainText('Save not confirmed')
 await source(page)
 await page.getByRole('button',{name:'View indicators for this evidence',exact:true}).click()
 await expect(panel.getByRole('button',{name:'Retry unchanged indicator',exact:true})).toBeVisible()
 await page.route('**/incidents/'+caseId+'/indicators?*',route=>route.fulfill({status:503,json:{}}))
 await panel.getByRole('button',{name:'Retry unchanged indicator',exact:true}).click()
 await expect(panel.getByText('Indicator observation recorded.',{exact:true})).toBeVisible()
 expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1])
 await expect(panel.getByRole('region',{name:'Last saved indicator'})).toContainText('retry.workflow.example')
 await expect(panel.getByRole('alert')).toContainText('Indicators unavailable')
})
test('validation and conflict are distinct and writes never retry automatically',async({page})=>{
 const panel=await open(page);await panel.getByText('Add indicator observation',{exact:true}).click()
 await panel.getByLabel('Indicator evidence ID',{exact:true}).fill(evidenceId)
 await panel.getByLabel('Indicator kind',{exact:true}).selectOption('domain')
 await panel.getByLabel('Indicator value',{exact:true}).fill('valid.workflow.example')
 let status=422,writes=0
 await page.route('**/evidence/'+evidenceId+'/indicators',route=>{writes++;return route.fulfill({status,json:{detail:'private'}})})
 await panel.getByRole('button',{name:'Record indicator',exact:true}).click()
 await expect(panel.getByRole('alert')).toContainText('Validation failed')
 await expect(panel.getByLabel('Indicator value',{exact:true})).toBeEnabled();expect(writes).toBe(1)
 status=409;await panel.getByRole('button',{name:'Record indicator',exact:true}).click()
 await expect(panel.getByRole('alert')).toContainText('Submission conflict')
 await panel.getByRole('button',{name:'Start a new submission',exact:true}).click()
 await expect(panel.getByRole('button',{name:'Confirm new submission',exact:true})).toBeVisible();expect(writes).toBe(2)
 await panel.getByRole('button',{name:'Keep pending submission',exact:true}).click()
 await expect(panel.getByLabel('Indicator value',{exact:true})).toBeDisabled()
 await page.setViewportSize({width:390,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
})
