"""Agent registration, scoped jobs and verified evidence provenance."""
from alembic import op
import sqlalchemy as sa

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('registered_by_id', sa.Uuid(), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], name=op.f('fk_agents_registered_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('token_sha256', name=op.f('uq_agents_token_sha256'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_registered_by_id'), ['registered_by_id'], unique=False)

    op.create_table('collection_jobs',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('selected_files', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'complete', 'cancelled')", name=op.f('ck_collection_jobs_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_collection_jobs_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_collection_jobs_incident_id_incidents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_collection_jobs_requested_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_jobs')),
    sa.UniqueConstraint('id', 'incident_id', name='uq_collection_jobs_id_incident')
    )
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_jobs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_jobs_requested_by_id'), ['requested_by_id'], unique=False)

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_job_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('collection_item_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('source_path', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=16), server_default='legacy', nullable=False))
        batch_op.create_unique_constraint('uq_evidence_job_item', ['collection_job_id', 'collection_item_id'])
        batch_op.create_foreign_key('fk_evidence_job_incident', 'collection_jobs', ['collection_job_id', 'incident_id'], ['id', 'incident_id'], ondelete='RESTRICT')
        batch_op.create_check_constraint(op.f('ck_evidence_verification_status'), "verification_status IN ('legacy', 'verified')")
        batch_op.create_check_constraint(op.f('ck_evidence_collection_provenance'),
            "(collection_job_id IS NULL AND collection_item_id IS NULL AND verification_status = 'legacy') OR "
            "(collection_job_id IS NOT NULL AND collection_item_id IS NOT NULL AND source_path IS NOT NULL "
            "AND collected_at IS NOT NULL AND verified_at IS NOT NULL AND verification_status = 'verified')")

    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_evidence_collection_provenance'), type_='check')
        batch_op.drop_constraint(op.f('ck_evidence_verification_status'), type_='check')
        batch_op.drop_constraint('fk_evidence_job_incident', type_='foreignkey')
        batch_op.drop_constraint('uq_evidence_job_item', type_='unique')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('collected_at')
        batch_op.drop_column('source_path')
        batch_op.drop_column('collection_item_id')
        batch_op.drop_column('collection_job_id')

    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_jobs_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_collection_jobs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_collection_jobs_agent_id'))

    op.drop_table('collection_jobs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_registered_by_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
